import Providers from "@utils/Providers";
import "@styles/globals.css";
import type { Metadata } from "next";
import React from "react";
import Header from "@components/Header";
import Footer from "@components/Footer";
import FloatingButton from "@components/FloatingButton";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: "../public/font/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pretendard.variable}`}>
      <body className="min-w-[390px] font-pretendard font-medium desktop:min-w-[1080px]">
        <Providers>
          <Header />
          {children}
          <Footer />
          <FloatingButton />
        </Providers>
      </body>
    </html>
  );
}
