import Providers from "@utils/Provider";
import "@styles/globals.css";
import type { Metadata } from "next";
import React from "react";
import Header from "@components/Header";
import Footer from "@components/Footer";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: "../public/font/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pretendard.variable}`}>
      <body className="font-pretendard font-medium">
        <Providers>
          <Header />
          {children}
          {/* 임시로 지정한 가운데 영역 */}
          <div className="h-[500px] bg-white" />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
